name: motive.io
favicon: null
layout_spectrum: 0.5045175068080425
typography_spectrum: 0.6737441343721002
title: Motive.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17292d'
    - '#6bb9b9'
    - '#ea6625'
    - '#ffffff'
    - '#e62949'
  brandStrength: 1
  lightness: 0.9152086286339909
  saturation: 0.1875
  rhythmicContrast: 0.5728037117514759
purpose: []
