name: motive
favicon: null
layout_spectrum: 0.5045175068080425
typography_spectrum: 0.6737441343721002
title: Motive.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.609199644997716
  lightness: 0.9152086286339909
  saturation: 0.34816255304031074
  rhythmicContrast: 0.5728037117514759
purpose: []
