name: motive.io
favicon: null
layout_spectrum: 0
typography_spectrum: 0.30926
title: Motive.io
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17292d'
    - '#6bb9b9'
    - '#ea6625'
    - '#ffffff'
    - '#e62949'
  brandStrength: 0.1875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
